### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by JekRock** [bobocode-projects/java-core-exercises#22]
[Linked queue](https://github.com/boy4uck/java-core-exercises/tree/master/linked-queue) and [Concurrent linked queue simple](https://github.com/bobocode-projects/java-core-exercises/tree/master/concurrent-linked-queue-simple) links are broken in the [README](https://github.com/bobocode-projects/java-core-exercises/blob/master/README.md)

**Comment by kortov** [comment]
you can just create a PR :)

**Comment by JekRock** [comment]
I could but I didn't know what [Concurrent linked queue simple](https://github.com/bobocode-projects/java-core-exercises/tree/master/concurrent-linked-queue-simple) supposed to be)

**Comment by kortov** [comment]
it was removed in https://github.com/bobocode-projects/java-core-exercises/commit/a15701becbcb3e059b7842708a4b74942351b8a9 (I think on purpose)

**Comment by JekRock** [comment]
Got it. Thanks for the info
